### ISSUE TITLE
Add unit tests for CO2 functionality

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/rSOILWAT2#42]

**Comment by Zachary-Kramer** [comment]
What is the scope of this? Meaning is anything in the src folder included, such as R_Lib? If this is strictly limited to the R folder, the only thing I can think of to test is setting/getting variables of the class, along with the swClear method.

**Comment by dschlaep** [comment]
I agree that there is not much to test on the R/ side and I agree that the SOILWAT2 submodule code in the src/ folder should be tested in the SOILWAT2 repository. However, I really want to see us to move toward formally and continuously testing our code. I set up our R packages to use unit testing through the 'testthat' framework and to report code coverage with the 'covr' framework and linked it to the continuous integration checking by 'travis-ci' and 'coveralls'.

Ideally, I would like us to write unit tests (and documentation) whenever we write code.

The SOILWAT2 repository is not yet set up with GoogleTest, but I would really appreciate if you take time to do that. And then add tests for the CO2 code there too.

**Comment by dschlaep** [comment]
Hadley Wickham has section in his (online) book that provides a nice overview of unit testing in R: http://r-pkgs.had.co.nz/tests.html
