### ISSUE TITLE
Cannot open file Input/carbon.in: No such file or directory

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSOILWAT2#50]
This message occurs during SOILWAT2 execution via rSOILWAT2. It does not occur in SOILWAT2 standalone.

_read_inputs() is called, which reads the .in files and finishes by calling calculate_co2_multipliers(), which attempts to read carbon.in, but cannot find it.

Furthermore, if I duplicate the calculate_co2_multipliers() function call to certain parts of the model I can get it to recognize the file, but I don't understand how it's working because those placements seem problematic. This should be the path to go down to solve this bug.

It's worth noting that the placement of calculate_co2_multipliers() hasn't changed in months and has always worked. My biggest most recent changes were adding a constructor and merging master into rSOILWAT2.

**Comment by Zachary-Kramer** [comment]
The constructor is not at fault, and there are no other recent significant changes to how SW_Carbon works, so this will be a bit harder to debug

**Comment by Zachary-Kramer** [comment]
I've found the immediate cause, but not the root cause.

_read_inputs() current working directory, when called by rSOILWAT2, is the project directory. When called by SOILWAT2, it is the input directory. Thus, something is wrong with the R side.

The reason why the other .in files can be read-in is that carbon.in is always read-in during the _read_inputs() call, but the other .in files are only read-in here if R did not provide input data. This means the model will fail here if a user does not provide input data. However, the common use case is using onGetInputDataFromFiles (which reads in everything but carbon.in), which for some reason is in the correct directory.

onGetInputDataFromFiles being in the correct directory explains why placing calculate_co2_multipliers there found the file. Unfortunately, the call to calculate_co2_multipliers is useless here because the constructor is called afterwards and erases the data that was read in. I could change my constructor to not initialize my variables (so that it would only use memset), but there would still be a critical bug when input is not provided. Solving the root cause is the better way.

_This could exist on master branch. I merged master into my branch recently which is around when this started occuring. @dschlaep do you have any insight into why this might be occuring?_

**Comment by dschlaep** [comment]
I don't have much to say about this issue. I have almost exclusively been using rSOILWAT2 via rSFSW2, i.e., reading in the default inputs with code 

```
rSOILWAT2::sw_inputDataFromFiles(dir = dir_in_sw, files.in = swFilesIn)
```

as called from `rSFSW2::read_SOILWAT2_FileDefaults` via `rSFSW2::simulate_SOILWAT2_experiment`. That is the rSFSW2 function sets the directory explicitly which is translated by the R function `rSOILWAT2::sw_inputDataFromFiles` to the option `-d PATH` for  the C function `onGetInputDataFromFiles`. I assumes this is why in this use case the working directory is set correctly.

**Comment by Zachary-Kramer** [comment]
This issue is ultimately complex relative to the amount of time I have available. I can't think of any valid workarounds that I could do in SOILWAT2 alone. I also can't identify any recent changes that may have caused this. However, if I force the call to C_start to use to my input directory (Soilwat2_defaults/Input), it can find carbon.in, continue execution, and the output is normal.

@dschlaep can you think of any consequences of me passing in the input directory to sw_exec in rSOILWAT2? Also, I merged the most recent rSFSW2 commits into my CO2 branch and got hit with the error " ERROR: vegetation values contain NA.", which I believe is because the biomass values are NA if they aren't being used. Are your biomass values _not_ NA if their respective compositions are set to 0? (e.g. I'm only using Forb so all other PFTs have NA biomass)

**Comment by Zachary-Kramer** [comment]
This issue was closed in rSFSW2 by passing in the input directory to SOILWAT2::C_start(). I don't observe any negative consequences.
