### ISSUE TITLE
Weather database fails to get created. Any known solutions?

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSOILWAT2#59]
**Preface**

Recently I had to format by computer and hence had to reinstall R and all of its packages. I'm using the same exact rSFSW2 project and source code as I did before, but now I'm hitting a weird error and was wondering if anyone has seen it before or knows what may be causing it. If not, I can at least post the solution here when I figure it out.

**Error**

rSFSW2 calls make_dbw, which fails with 

> Error: rSOILWAT2::dbW_createDatabase(dbFilePath = SFSW2_prj_meta[["fnames_in"]][["fdbWeather"]],  .... is not TRUE

I debugged this further, and the code fails in .create_dbw() when inserting values into 'Meta' (the 5th line of the function). Specifically, R says .local(...) has an unused parameter `(params = list(
		Desc = c("Version", "Compression_type"),
		Value = c(rSW2_glovars$dbW_version, rSW2_glovars$blob_compression_type)))`

**Other info**

The code is certainly valid, so I've no idea why it thinks the parameter is unused, and I've no idea what could be set up incorrectly since I'm using a project that I know works. This is certainly a set up issue, whether it's somehow my project or more likely my system environment.

The only thing I can think of is perhaps a package needs a newer version? I'm using R version 3.3 with DBI 0.5. I also tried using DBI 0.7, despite it having being built on R 3.4.2, but it made no difference.

This is high priority because rSFSW2 will no longer let me reuse a daily weather database (disabling prep_inputs requires "SFSW2_prj_inputs", which I don't have?).

Thanks ahead of time for any information

@dschlaep -- tagging you in case you don't get notified of new issues by email

**Comment by dschlaep** [comment]
This may be that installed version of rSFSW2 expects a newer version of rSOILWAT2 than installed?

Alternatively, if you are reusing an existing weather database, it may be due to the currently installed versions of rSFSW2 and/or rSOILWAT2 requiring a newer weather database version? Check with dbW_check_version()

If the weather database version is the culprit, update it with the appropriate upgrade functions, see ?dbW_upgrade

**Comment by Zachary-Kramer** [comment]
I installed R 3.4.2 and all of the needed packages, which solved this for me.
