### ISSUE TITLE
Add support for calculating CO2 multipliers from R data

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSOILWAT2#70]
e.g. rSOILWAT2 will send a list of PPM values to SOILWAT2, and SOILWAT2 needs to be able to find the right scenario and use the PPM values like what is currently done with carbon.in

The current limitation is figuring out how to communicate this data and not have it be one giant string

Issue stemmed from #57

**Comment by Zachary-Kramer** [comment]
This has become an increasingly poor implementation. It seems that the prototype of swCarbon needs to hold all PPM values, along with the class being able to write the entire file. What this means is that the swCarbon class has ~30,000 characters of data just for simple functionality, along with being tedious to maintain. Maybe carbon.in should not in fact be a .in file because it does not hold settings, only data. At this point it's too late to change, just food for thought.

**Comment by Zachary-Kramer** [comment]
Upon further review, there is no need for R to have access to the PPM values. In fact, there is no need for the input file carbon.in. The PPM values will only be stored in SOILWAT2 memory.

@dschlaep do you see a problem with this approach?

**Comment by Zachary-Kramer** [comment]
I've implemented the above solution, which should solve the R requirement in #57, and is more efficient than using a file handler or reading data from an R object. Just waiting for confirmation that there isn't a flaw in this approach.

**Comment by dschlaep** [comment]
I guess that `PPM values` means the yearly values of atmospheric carbon dioxide concentrations in units of ppm where ppm = parts per million?

I don't understand your suggestion:
- Why do you say: `no need for R to have access to the PPM values. In fact, there is no need for the input file carbon.in.`? I disagree because `rSFSW2` must be able to set different yearly values of carbon dioxide concentration from run to run.
- What is the difference for you between "user input" and "appending scenarios"? As in `I believe we can do this because the PPM values should not be changed based on user input, and rather should be permanently changed via appending scenarios`. This seems to be the same to me.
- Why does the `swCarbon` class require so much code as you suggest by `What this means is that the swCarbon class has ~30,000 characters of data just for simple functionality`? All what it needs to do is to set/read a numeric vector and know which calendar years the vector represents.

I would say there is no need for the `SOILWAT2` input file `carbon.in` to handle multiple datasets. One file `carbon.in` only needs to contain yearly data of carbon dioxide concentrations for one scenario. We will have umpteen such scenarios.

At the `rSFSW2` level, I imagine a spreadsheet where rows = calendar years and columns = scenarios. For a specific run, `rSFSFW2` picks a specific column, subsets rows to simulation years and sends this numeric vector to `rSOILWAT2`. I don't see why this should be a big deal?

**Comment by Zachary-Kramer** [comment]
Yes, by PPM values I meant CO2 ppm.

Why does rSFSW2 need to be able to set different yearly values of CO2 concentrations? I thought the whole point of having scenarios was to account for this: if a user wants to change the yearly ppm values, they should change the scenario. Is this incorrect?

> What is the difference for you between "user input" and "appending scenarios"?

I meant that the data that is in carbon.in should not be changed on a per-run basis via user input. For instance, the values in prod.in can be changed by the user, whereas the ppm values for a scenario should not be changed by the user. If the user wants different values, he/she should append a scenario and reference it in their input.

> Why does the swCarbon class require so much code as you suggest

You mentioned that rSOILWAT2 does not have access to the .in files. So, I understood that as: swCarbon also needs to hold the ppm values. All of the other .in classes hold every single line of the respective file, along with separating the file's values into the respective slots in the prototype. If I were to do this for ppm (which I've done locally already...), swCarbon would hold many characters of data.

> At the rSFSW2 level, I imagine a spreadsheet where rows = calendar years and columns = scenarios. For a specific run, rSFSFW2 picks a specific column, subsets rows to simulation years and sends this numeric vector to rSOILWAT2. I don't see why this should be a big deal?

I hadn't thought about that use case. I assumed that the user should always be using an existing scenario or adding a new one. Given the shortage of time, I don't think it's feasible to implement that at the moment, unless it's absolutely required (even then, one could make do with creating a temporary scenario). Maybe a future enhancement where a user can provide yearly ppm without a scenario? As far as the big deal, I'm so short on time that adding any additional functionality isn't ideal. Getting rSOILWAT2 to be able to send ppm data to SOILWAT2 already took up a few hours between learning how the S4 class wants the data and how Rinternals wants me to access it.

**Comment by dschlaep** [comment]
> If a user wants to change the yearly ppm values, they should change the scenario. Is this incorrect?
--> Yes.

> swCarbon also needs to hold the ppm values.
--> No, see `swWeatherData` and its prototype or `swClear` method. It is initialized to `matrix(data=c(1:366,rep(999,366*3)),nrow=366,ncol=4)`.
And it's `swWriteLines` method loops over the rows which uses 3 lines of code and not 366 lines.
I suggest you do something similar for `swCarbon`.

> I assumed that the user should always be using an existing scenario or adding a new one.
--> What do you mean with `existing scenario or adding a new one`? To where? 
There are two input mechanisms in `rSFSW2` to handle run-specific inputs: (i) lookup-folders and (ii) csv-spreadsheets. Which mechanism do you plan to implement for carbon data?

**Comment by Zachary-Kramer** [comment]
Well it seems the requirements for CO2 were not laid out very well. During development, I don't recall discussion of custom yearly values.

I'm confused about the actual implementation of the rSFSW2 input. I have not dealt with adding input as either look-up folders or CSV spreadsheets, so I have a few questions:

1) Why does rSFSW2 need the tr_xxxx folders? They hold the same .in files that are in SoilWat2_Defaults/input. Why must it exist in more than one place?

2) If I add a tr_carbon folder, and add the carbon.in file to it, what does rSFSW2 do with it? e.g. what's the purpose of rSFSW2 holding the files when SOILWAT2 holds the mechanism for reading them? rSOILWAT2 also holds the contents of the files in memory (with infiletext). Why do the .in files need to be in 4 places (SoilWat2_Default, tr_xxxx, rSOILWAT2/src/testing/input, rSOILWAT2 code)?

3) The CSV-spreadsheets seem like the most intuitive choice, for both users and for readability. Do you think it is the best option?

4) If I initialize the prototype to 999, as opposed to passing in the data for all scenarios (which is absurd anyways), then the user always has to override the values if they want to use CO2 effects. To handle this, it seems that the first step is to add a CSV file with the same exact data as carbon.in, but formatted differently. Then I would have to implement, in rSFSW2, the ability to search the CSV file for the requested scenario, format it, overwrite the ppm data in the prototype, then pass it to rSOILWAT2. Is this correct?

Apologies if some of my questions are a bit confusing. I haven't touched this aspect of rSFSW2 and don't have much time to do so. Are there other undocumented enhancements missing from CO2 that need to be implemented?

**Comment by dschlaep** [comment]
> Re 1

See https://github.com/Burke-Lauenroth-Lab/rSFSW2/issues/216

> Re 2

See https://github.com/Burke-Lauenroth-Lab/rSFSW2/issues/217

> Re 3

Prototype is in `rSOILWAT2`. Simulation projects are dealt with by `rSFSW2`. I see no problem with the need for the user the specify carbon dioxide concentration values for each newly generated object of class `swCarbon`.
