### ISSUE TITLE
CO2 pull request failing

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/rSOILWAT2#73]
The exact reason isn't known, though it's likely due to the input data in the tests. 

See issue #54. Examples 1 and 2 will need to be updated again to hold new input data. Here is my [sw_input.Rdata](https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/files/1464957/sw_input.zip) from one of my runs where CO2 was enabled (index 1 = default scenario, 2/3 = RCP85 scenario), for reference. Note that this input has the "carbon" class, along with some modifications to other classes (like the CO2Coefficients slot).

The first step to solving this should just be updating the examples.

**Comment by dschlaep** [comment]
All examples are updated (see commit 099fab57654e86812307ba40bd7b4a2de6b9fcda), but code is still failing.
I see that there are at least two problems with the pull-request checks failing:
- SOILWAT2 source code on master and development branch have conflicts; I guess that this will be resolved automatically once the CO2-effects development branch of SOILWAT2 has been merged into master. See message from checks:
> This branch has conflicts that must be resolved to resolve conflicts before continuing. Conflicting files: src

- "ERROR: Cannot open file Input/carbon.in: No such file or directory" --> new issue #74

**Comment by dschlaep** [comment]
Currently, issue #78 remains.

**Comment by dschlaep** [comment]
Currently, issue https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/issues/81 presented itself.

**Comment by dschlaep** [comment]
Commit https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/commit/f4327ae6b56830c368fe2ec882da6a1bd5fc6611 closes issue #81 which was preventing this one from closing.
